"""
Quant Analysis router
=====================
Serves two JSON files generated by the daily inference pipeline:
  • quant_market.json    — market-wide technical + institutional + macro data
  • pattern_signals.json — bullish chart pattern scan results

Both are fetched from GitHub raw (same pattern as signals router) with 1-hour TTL.
"""
import asyncio
import logging
import os
from datetime import datetime, timedelta
from typing import Optional

from fastapi import APIRouter, HTTPException

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/quant", tags=["Quant"])

# ── GitHub base URL ───────────────────────────────────────────────────────────
# Derived from the existing GITHUB_RESULTS_URL env var (strip df_kelly.csv suffix)
_BASE_URL = os.getenv("GITHUB_RESULTS_URL", "").replace("df_kelly.csv", "")
QUANT_MARKET_URL  = _BASE_URL + "quant_market.json"   if _BASE_URL else ""
PATTERN_URL       = _BASE_URL + "pattern_signals.json" if _BASE_URL else ""

CACHE_TTL = timedelta(hours=1)

# ── In-memory caches (separate locks per resource) ───────────────────────────
_market_cache:      Optional[dict] = None
_market_cache_time: Optional[datetime] = None
_market_lock: asyncio.Lock = asyncio.Lock()

_pattern_cache:      Optional[dict] = None
_pattern_cache_time: Optional[datetime] = None
_pattern_lock: asyncio.Lock = asyncio.Lock()


async def _fetch_json(url: str) -> Optional[dict]:
    """Fetch a JSON file from a URL. Returns None on error."""
    if not url:
        return None
    try:
        import httpx
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.get(url)
            if r.status_code != 200:
                logger.warning(f"[quant] fetch failed ({r.status_code}): {url}")
                return None
            return r.json()
    except Exception as e:
        logger.warning(f"[quant] fetch error: {e}")
        return None


# ════════════════════════════════════════════════════════════════════════════════
# GET /api/quant  — market-wide quantitative data
# ════════════════════════════════════════════════════════════════════════════════

@router.get("")
async def get_quant_market():
    """
    Daily market-wide quantitative indicators:
    TAIEX technicals, institutional flow, breadth history,
    margin/short summary, sector rotation.
    """
    global _market_cache, _market_cache_time

    async with _market_lock:
        now = datetime.utcnow()
        if (_market_cache is not None
                and _market_cache_time is not None
                and now - _market_cache_time < CACHE_TTL):
            return _market_cache

        data = await _fetch_json(QUANT_MARKET_URL)
        if data:
            _market_cache      = data
            _market_cache_time = now
            logger.info("[quant] quant_market.json loaded from GitHub")
            return data

        # ── Fallback: return stale cache rather than 404 ──
        if _market_cache is not None:
            logger.warning("[quant] GitHub unavailable — serving stale quant_market cache")
            return _market_cache

        raise HTTPException(status_code=503,
                            detail="量化市場資料暫不可用（尚未生成或 GitHub 連線失敗）")


# ════════════════════════════════════════════════════════════════════════════════
# GET /api/quant/patterns  — chart pattern scan results
# ════════════════════════════════════════════════════════════════════════════════

@router.get("/patterns")
async def get_pattern_signals(dual_confirm_only: bool = False):
    """
    Bullish chart pattern scan results for ~2,500 stocks.

    Query params:
      dual_confirm_only (bool) — if true, only return stocks with
                                  both pattern score ≥ 60 AND alpha_rank ≤ 200.
    """
    global _pattern_cache, _pattern_cache_time

    async with _pattern_lock:
        now = datetime.utcnow()
        if (_pattern_cache is not None
                and _pattern_cache_time is not None
                and now - _pattern_cache_time < CACHE_TTL):
            data = _pattern_cache
        else:
            data = await _fetch_json(PATTERN_URL)
            if data:
                _pattern_cache      = data
                _pattern_cache_time = now
                logger.info("[quant] pattern_signals.json loaded from GitHub")
            elif _pattern_cache is not None:
                logger.warning("[quant] GitHub unavailable — serving stale pattern cache")
                data = _pattern_cache
            else:
                raise HTTPException(
                    status_code=503,
                    detail="型態掃描資料暫不可用（尚未生成或 GitHub 連線失敗）"
                )

    # ── Optional filter ──
    if dual_confirm_only:
        filtered = [s for s in data.get("signals", []) if s.get("dual_confirm")]
        return {**data, "signals": filtered,
                "patterns_found": len(filtered)}

    return data


# ════════════════════════════════════════════════════════════════════════════════
# POST /api/quant/cache/refresh  — force cache invalidation
# ════════════════════════════════════════════════════════════════════════════════

@router.post("/cache/refresh")
async def refresh_quant_cache():
    """Force both quant caches to reload from GitHub on next request."""
    global _market_cache_time, _pattern_cache_time
    async with _market_lock:
        _market_cache_time = None
    async with _pattern_lock:
        _pattern_cache_time = None
    logger.info("[quant] Cache invalidated via POST /api/quant/cache/refresh")
    return {"status": "ok", "message": "Quant caches cleared — will reload on next request"}
