"""
Reports router — LLM market summary
=====================================
Serves the Claude-generated market_summary.json from GitHub.
Generated by run_daily_inference.py after each inference run.
"""
import io
import logging
import os
from datetime import datetime, timedelta
from typing import Optional

from fastapi import APIRouter
from pydantic import BaseModel

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/reports", tags=["Reports"])

# GitHub URL for market_summary.json
_BASE = os.getenv("GITHUB_RESULTS_URL", "").replace("df_kelly.csv", "")
REPORT_URL = _BASE + "market_summary.json" if _BASE else ""

_report_cache: Optional[dict] = None
_report_cache_time: Optional[datetime] = None
_REPORT_TTL = timedelta(hours=1)


class ReportResponse(BaseModel):
    date: str
    summary: str
    model: str = "claude-3-haiku-20240307"
    top10: list = []
    market_data: dict = {}
    available: bool = True


async def _load_report() -> Optional[dict]:
    if not REPORT_URL:
        return None
    try:
        import httpx
        async with httpx.AsyncClient(timeout=10) as client:
            r = await client.get(REPORT_URL)
            if r.status_code != 200:
                return None
        return r.json()
    except Exception as e:
        logger.warning(f"Report fetch failed: {e}")
        return None


@router.get("/latest", response_model=ReportResponse)
async def get_latest_report():
    """最新 Claude AI 市場分析報告"""
    global _report_cache, _report_cache_time

    if _report_cache and _report_cache_time and datetime.now() - _report_cache_time < _REPORT_TTL:
        return ReportResponse(**_report_cache, available=True)

    data = await _load_report()
    if data:
        _report_cache = data
        _report_cache_time = datetime.now()
        return ReportResponse(**data, available=True)

    return ReportResponse(
        date=datetime.today().strftime("%Y-%m-%d"),
        summary="⏳ 今日報告生成中，請稍後再試。\n推論完成後，Claude 將自動生成市場分析。",
        available=False,
    )


@router.post("/cache/refresh")
async def refresh_report_cache():
    """強制重新載入報告快取"""
    global _report_cache, _report_cache_time
    _report_cache = None
    _report_cache_time = None
    data = await _load_report()
    if data:
        _report_cache = data
        _report_cache_time = datetime.now()
        return {"status": "ok", "date": data.get("date")}
    return {"status": "unavailable"}
