"""
Simulation router
=================
Serves the pre-computed investment simulation backtest result.
The JSON is generated by V6/marketmamba/backtest/sim_engine.py
during each daily inference run and pushed to GitHub.
"""
import json
import logging
import os
import pathlib
from datetime import datetime, timedelta
from typing import Optional

import httpx
from fastapi import APIRouter

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/sim", tags=["Simulation"])

GITHUB_RESULTS_URL = os.getenv("GITHUB_RESULTS_URL", "")
GITHUB_SIM_URL = GITHUB_RESULTS_URL.replace("df_kelly.csv", "sim_backtest.json") if GITHUB_RESULTS_URL else ""

# Local file fallback for dev mode
_LOCAL_SIM_PATH = (
    pathlib.Path(__file__).resolve().parent.parent.parent.parent
    / "V6" / "results" / "sim_backtest.json"
)

_sim_cache: Optional[dict] = None
_sim_cache_time: Optional[datetime] = None
CACHE_TTL = timedelta(hours=1)


@router.get("/backtest")
async def get_sim_backtest():
    """投資模擬回測 — 基於真實收盤價的每日損益曲線"""
    global _sim_cache, _sim_cache_time

    if _sim_cache and _sim_cache_time and datetime.now() - _sim_cache_time < CACHE_TTL:
        return _sim_cache

    # Try GitHub (production)
    if GITHUB_SIM_URL:
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                r = await client.get(GITHUB_SIM_URL)
                if r.status_code == 200:
                    _sim_cache = r.json()
                    _sim_cache_time = datetime.now()
                    logger.info(
                        f"sim_backtest loaded from GitHub: "
                        f"{_sim_cache.get('trading_days', 0)} days, "
                        f"return={_sim_cache.get('total_return_pct', 0):+.2f}%"
                    )
                    return _sim_cache
                logger.warning(f"sim_backtest.json GitHub fetch failed: {r.status_code}")
        except Exception as e:
            logger.warning(f"sim_backtest GitHub load error: {e}")

    # Try local file (dev mode)
    if _LOCAL_SIM_PATH.exists():
        try:
            with open(_LOCAL_SIM_PATH, encoding="utf-8") as f:
                _sim_cache = json.load(f)
            _sim_cache_time = datetime.now()
            logger.info(f"sim_backtest loaded from local file")
            return _sim_cache
        except Exception as e:
            logger.warning(f"sim_backtest local load error: {e}")

    return {
        "equity_curve": [],
        "trading_days": 0,
        "error": "Backtest data not yet available. Run daily inference first.",
    }
