"""
Simulation router
=================
Serves the signal-driven robot backtest result (sim_backtest.json)
and IC/ICIR analysis (ic_analysis.json).

Both JSONs are generated by V6/marketmamba/backtest/ during each
daily inference run and pushed to GitHub.
"""
import json
import logging
import os
import pathlib
from datetime import datetime, timedelta
from typing import Optional

import httpx
from fastapi import APIRouter

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/sim", tags=["Simulation"])

_GITHUB_BASE = os.getenv(
    "GITHUB_RESULTS_URL", ""
).replace("df_kelly.csv", "")   # → .../V6/results/

GITHUB_SIM_URL = _GITHUB_BASE + "sim_backtest.json" if _GITHUB_BASE else ""
GITHUB_IC_URL  = _GITHUB_BASE + "ic_analysis.json"  if _GITHUB_BASE else ""

_LOCAL_RESULTS = (
    pathlib.Path(__file__).resolve().parent.parent.parent.parent
    / "V6" / "results"
)
_LOCAL_SIM_PATH = _LOCAL_RESULTS / "sim_backtest.json"
_LOCAL_IC_PATH  = _LOCAL_RESULTS / "ic_analysis.json"

_sim_cache:      Optional[dict] = None
_sim_cache_time: Optional[datetime] = None
_ic_cache:       Optional[dict] = None
_ic_cache_time:  Optional[datetime] = None
CACHE_TTL = timedelta(hours=1)


async def _load_json(github_url: str, local_path: pathlib.Path) -> Optional[dict]:
    """Generic helper: try GitHub, fall back to local file."""
    if github_url:
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                r = await client.get(github_url)
                if r.status_code == 200:
                    return r.json()
                logger.warning(f"GitHub fetch failed ({r.status_code}): {github_url}")
        except Exception as e:
            logger.warning(f"GitHub fetch error: {e}")

    if local_path.exists():
        try:
            with open(local_path, encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.warning(f"Local file load error: {e}")

    return None


@router.get("/backtest")
async def get_sim_backtest():
    """
    訊號驅動投資機器人回測結果。
    包含：帳戶摘要、目前持倉、觀察清單、Equity curve（含 TWII 基準）、交易紀錄。
    """
    global _sim_cache, _sim_cache_time

    if _sim_cache and _sim_cache_time and datetime.now() - _sim_cache_time < CACHE_TTL:
        return _sim_cache

    data = await _load_json(GITHUB_SIM_URL, _LOCAL_SIM_PATH)
    if data:
        _sim_cache = data
        _sim_cache_time = datetime.now()
        s = data.get("summary", {})
        logger.info(
            f"sim_backtest loaded: {data.get('trading_days', 0)} days  "
            f"return={s.get('total_return_pct', 0):+.2f}%  "
            f"positions={s.get('current_positions', 0)}"
        )
        return data

    return {
        "trading_days": 0,
        "summary": {},
        "current_holdings": [],
        "watchlist": [],
        "equity_curve": [],
        "benchmark_curve": [],
        "transactions": [],
        "error": "Backtest data not yet available. Run daily inference first.",
    }


@router.get("/ic")
async def get_ic_analysis():
    """
    模型預測力驗證 (IC / ICIR)。
    包含：各期 IC 均值、ICIR、t 統計量，及每日 IC 序列與滾動 IC。
    """
    global _ic_cache, _ic_cache_time

    if _ic_cache and _ic_cache_time and datetime.now() - _ic_cache_time < CACHE_TTL:
        return _ic_cache

    data = await _load_json(GITHUB_IC_URL, _LOCAL_IC_PATH)
    if data:
        _ic_cache = data
        _ic_cache_time = datetime.now()
        s = data.get("horizon_summary", {}).get("5d", {})
        logger.info(
            f"ic_analysis loaded: IC_5d={s.get('mean_ic', 'N/A')}  "
            f"ICIR={s.get('icir', 'N/A')}"
        )
        return data

    return {
        "archive_count":   0,
        "horizon_summary": {},
        "ic_series_5d":    [],
        "rolling_ic_5d":   [],
        "error": "IC analysis not yet available. Run daily inference first.",
    }


@router.post("/cache/refresh")
async def refresh_sim_cache():
    """手動清除 sim 快取，下次請求時重新從 GitHub 拉取。"""
    global _sim_cache, _sim_cache_time, _ic_cache, _ic_cache_time
    _sim_cache = _sim_cache_time = None
    _ic_cache  = _ic_cache_time  = None
    return {"status": "ok", "message": "Sim + IC cache cleared"}
